export const fontFamilyOptions = [
    'Arial',
    'Arial Black',
    'Comic Sans MS',
    'Courier New',
    'Georgia',
    'Times New Roman',
    'Verdana',
    'Trebuchet MS',
    'Lucida Console',
    'Tahoma',
    'Impact',
    'Gill Sans',
    'Helvetica',
    'Palatino Linotype',
    'Tahoma',
    'Century Gothic',
    'Garamond',
    'Bookman Old Style',
    'Arial Narrow',
    'Frank Ruhl',
    'Consolas',
    'Fira Sans',
    'Lato',
    'Roboto',
    'Open Sans',
    'Source Sans Pro',
    'Montserrat',
    'PT Sans',
    'Droid Sans',
    'Ubuntu',
    'Raleway',
    'Poppins',
    'Merriweather',
    'Playfair Display',
    'Noto Sans',
    'Lora',
    'Oxygen',
    'Droid Serif',
    'Inconsolata',
    'Quicksand',
    'Oswald',
    'Exo',
    'Roboto Condensed',
    'Karla',
    'Arvo',
    'Cabin',
    'Yanone Kaffeesatz',
    'Bebas Neue',
    'Pangolin',
    'Muli',
    'Rokkitt',
    'Overpass',
    'Spectral',
    'Asap',
    'Work Sans',
    'Zilla Slab',
    'Slabo 27px',
    'Varela Round',
    'Maven Pro',
    'Rajdhani',
    'Noto Serif',
    'Noto Sans JP',
    'Fira Code',
  ];
  